<a href="https://colab.research.google.com/github/gamodilac/roboticHW/blob/main/BT_W2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#exercise
#Tìm số lượng huy chương của một mục bất kì
#tìm số huy chương vàng theo môn thi cá nhân cảu một nước
#lọc ra các thể loại huy chương, tính mean, tính tổng,...

In [6]:
import pandas as pd
import numpy as np
url='http://winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data.head(21)

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
0,1924,Chamonix,Skating,Figure skating,AUT,individual,M,Silver
1,1924,Chamonix,Skating,Figure skating,AUT,individual,W,Gold
2,1924,Chamonix,Skating,Figure skating,AUT,pairs,X,Gold
3,1924,Chamonix,Bobsleigh,Bobsleigh,BEL,four-man,M,Bronze
4,1924,Chamonix,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
5,1924,Chamonix,Biathlon,Biathlon,FIN,military patrol,M,Silver
6,1924,Chamonix,Skating,Figure skating,FIN,pairs,X,Silver
7,1924,Chamonix,Skating,Speed skating,FIN,10000m,M,Gold
8,1924,Chamonix,Skating,Speed skating,FIN,10000m,M,Silver
9,1924,Chamonix,Skating,Speed skating,FIN,1500m,M,Gold
10,1924,Chamonix,Skating,Speed skating,FIN,5000m,M,Gold
11,1924,Chamonix,Skating,Speed skating,FIN,5000m,M,Silver
12,1924,Chamonix,Skating,Speed skating,FIN,500m,M,Bronze
13,1924,Chamonix,Skating,Speed skating,FIN,combined (4 events),M,Bronze
14,1924,Chamonix,Skating,Speed skating,FIN,combined (4 events),M,Gold
15,1924,Chamonix,Skiing,Cross Country S,FIN,18km,M,Bronze
16,1924,Chamonix,Biathlon,Biathlon,FRA,military patrol,M,Bronze
17,1924,Chamonix,Curling,Curling,FRA,curling,M,Bronze
18,1924,Chamonix,Skating,Figure skating,FRA,pairs,X,Bronze
19,1924,Chamonix,Bobsleigh,Bobsleigh,GBR,four-man,M,Silver
20,1924,Chamonix,Curling,Curling,GBR,curling,M,Gold

In [8]:
#Lọc chỉ lấy huy chương vàng
url='http://winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data = data.set_index(data['Medal'])
data.loc['Gold']

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
Medal,,,,,,,,
Gold,1924,Chamonix,Skating,Figure skating,AUT,individual,W,Gold
Gold,1924,Chamonix,Skating,Figure skating,AUT,pairs,X,Gold
Gold,1924,Chamonix,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
Gold,1924,Chamonix,Skating,Speed skating,FIN,10000m,M,Gold
Gold,1924,Chamonix,Skating,Speed skating,FIN,1500m,M,Gold
...,...,...,...,...,...,...,...,...
Gold,2006,Turin,Skiing,Alpine Skiing,USA,Alpine combined,M,Gold
Gold,2006,Turin,Skiing,Alpine Skiing,USA,giant slalom,W,Gold
Gold,2006,Turin,Skiing,Snowboard,USA,Half-pipe,M,Gold
Gold,2006,Turin,Skiing,Snowboard,USA,Half-pipe,W,Gold
Gold,2006,Turin,Skiing,Snowboard,USA,Snowboard Cross,M,Gold

In [27]:
# Lọc số lượng huy chương vàng của USA
url='http://winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data = data.set_index(data['Medal'])
data=data.loc['Gold']
data[data['NOC']=='USA'].head(10)

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
Medal,,,,,,,,
Gold,1924,Chamonix,Skating,Speed skating,USA,500m,M,Gold
Gold,1928,St. Moritz,Bobsleigh,Bobsleigh,USA,five-man,M,Gold
Gold,1928,St. Moritz,Bobsleigh,Skeleton,USA,individual,M,Gold
Gold,1932,Lake Placid,Bobsleigh,Bobsleigh,USA,four-man,M,Gold
Gold,1932,Lake Placid,Bobsleigh,Bobsleigh,USA,two-man,M,Gold
Gold,1932,Lake Placid,Skating,Speed skating,USA,10000m,M,Gold
Gold,1932,Lake Placid,Skating,Speed skating,USA,1500m,M,Gold
Gold,1932,Lake Placid,Skating,Speed skating,USA,5000m,M,Gold
Gold,1932,Lake Placid,Skating,Speed skating,USA,500m,M,Gold
Gold,1936,Garmisch-Partenkirchen,Bobsleigh,Bobsleigh,USA,two-man,M,Gold

In [31]:

url='http://winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
#print('Số lượng huy chương vàng của USA:',data['Medal'].count())
data[(data['Sport']=='Skiing')&(data['Medal']=='Gold')&(data['NOC']=='USA')]

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
250,1948,St. Moritz,Skiing,Alpine Skiing,USA,slalom,W,Gold
316,1952,Oslo,Skiing,Alpine Skiing,USA,giant slalom,W,Gold
317,1952,Oslo,Skiing,Alpine Skiing,USA,slalom,W,Gold
784,1972,Sapporo,Skiing,Alpine Skiing,USA,slalom,W,Gold
1122,1984,Sarajevo,Skiing,Alpine Skiing,USA,downhill,M,Gold
1123,1984,Sarajevo,Skiing,Alpine Skiing,USA,giant slalom,W,Gold
1125,1984,Sarajevo,Skiing,Alpine Skiing,USA,slalom,M,Gold
1436,1992,Albertville,Skiing,Freestyle Ski.,USA,moguls,W,Gold
1614,1994,Lillehammer,Skiing,Alpine Skiing,USA,downhill,M,Gold
1617,1994,Lillehammer,Skiing,Alpine Skiing,USA,super-G,W,Gold
1819,1998,Nagano,Skiing,Alpine Skiing,USA,super-G,W,Gold
1820,1998,Nagano,Skiing,Freestyle Ski.,USA,aerials,M,Gold
1821,1998,Nagano,Skiing,Freestyle Ski.,USA,aerials,W,Gold
1822,1998,Nagano,Skiing,Freestyle Ski.,USA,moguls,M,Gold
2056,2002,Salt Lake City,Skiing,Snowboard,USA,Half-pipe,M,Gold
2058,2002,Salt Lake City,Skiing,Snowboard,USA,Half-pipe,W,Gold
2301,2006,Turin,Skiing,Alpine Skiing,USA,Alpine combined,M,Gold
2302,2006,Turin,Skiing,Alpine Skiing,USA,giant slalom,W,Gold
2305,2006,Turin,Skiing,Snowboard,USA,Half-pipe,M,Gold
2307,2006,Turin,Skiing,Snowboard,USA,Half-pipe,W,Gold
2309,2006,Turin,Skiing,Snowboard,USA,Snowboard Cross,M,Gold